/* 公開連結頁的三語字典——逐字取自設計稿 `trip-share-public.html` 的 `S`
 * （Open Design 專案 e0f396c1-0fb8-48ff-9a11-996200cddadc）。
 *
 * 改過的地方：
 *   - 交通方式：設計稿的假資料用 car/walk/bus…；真的公開版本帶的是 App 的 `LegMode` 原始值，
 *     字取 App 的 `domain.legmode.*`（Domain/Resources/Localizable.xcstrings）。
 *   - 純文字那幾個字（it*）不在這裡：在 core.js 的 ITINERARY，跟 App 的字串目錄逐字對。
 *   - 設計稿的「退路」卡（fb*）沒有上線：spike 證實網頁登入＋刪除做得到，退路不需要。
 *   - `signinGo`／`stopFailed`：設計稿的登入鈕是 CloudKit JS 掛進來的 Apple 按鈕（稿裡只佔位）；
 *     這一頁不載 CloudKit JS，所以按鈕自己畫、字自己給。停止失敗設計稿沒畫，用 toast 講。
 */
export const LANGS = [
  { k: 'zh', lb: '中', html: 'zh-Hant' },
  { k: 'en', lb: 'EN', html: 'en' },
  { k: 'ja', lb: '日', html: 'ja' },
];

export const S = {
  zh: {
    days: '天', day: '第 %s 天', min: '%s 分', hr: '%s 小時', hrmin: '%s 小時 %s 分',
    undated: '日期未定', updated: '最後更新 %s',
    note: '這一頁是 TripEZGo 旅程的公開版本，開著就看得到，不需要安裝 App。',
    grid: '行程時間表，左右捲動可以看其他天',
    empty: '這一天還沒有安排。',
    loading: '正在打開這趟行程⋯',
    copyApp: '複製成我的旅程',
    copyAppNote: '已經有 TripEZGo 會直接打開 App，把這趟複製成你的旅程。還沒有的話，按下去會先把這條連結存進剪貼簿——<b>裝好之後打開 App，它就會接上這趟行程。</b>',
    savedHead: '連結已經存起來了',
    savedLede: '接著去取得 TripEZGo。裝好之後打開 App，它會問你要不要把這趟複製成你的旅程。',
    savedGo: '前往下載',
    copyText: '複製純文字行程', copiedText: '已複製純文字行程，貼進訊息或 LINE 就能讀',
    cal: '行事曆', map: '地圖', mapNone: '沒有座標，不在地圖上', mapAll: '這一天沒有標了位置的行程。',
    openApple: 'Apple 地圖', openGoogle: 'Google 地圖', close: '關閉',
    authorLink: '我是作者，管理這個連結',
    signinK: '管理這個連結', signinT: '用 iCloud 登入',
    signinWhy: '用建立這個連結的 iCloud 帳號登入，就能在這裡停止分享。',
    signinGo: '前往 Apple 登入',
    cancel: '取消',
    ownerK: '已用 iCloud 登入', ownerT: '你是這個連結的建立者',
    ownerWhy: '不再用 TripEZGo 了也沒關係，在這裡就能停止分享。',
    stop: '停止分享', signout: '登出',
    stopAsk: '停止分享這趟行程？',
    stopWhy: '停止後這條連結立刻失效，拿到連結的人都打不開。之後在 App 裡重新打開分享，會沿用同一條連結。',
    back: '返回', stopped: '已停止分享',
    stopFailed: '沒有停止成功，請再試一次',
    notOwnerT: '這個 iCloud 帳號不是建立者',
    notOwnerWhy: '只有建立這個連結的人能停止分享。換成建立者的帳號再登入一次，或請對方在 App 裡關掉。',
    stoppedT: '已停止分享',
    stoppedWhy: '這條連結已經失效。想再分享的話，在 TripEZGo 裡打開這趟旅程的公開連結，會沿用同一條。',
    err: '讀不到這趟行程', errWhy: '連結可能已經失效，或是對方停止分享了。',
    badT: '這條連結不完整',
    badWhy: '解不開這趟行程。請對方重新複製一次連結——網址最後那一段（# 之後）也要一起帶上。',
    learn: '看看 TripEZGo 是什麼',
    modes: { walking: '步行', driving: '開車', cycling: '騎車', transit: '大眾運輸', other: '其他' },
  },
  en: {
    days: 'days', day: 'Day %s', min: '%s min', hr: '%s h', hrmin: '%s h %s m',
    undated: 'Dates not set', updated: 'Last updated %s',
    note: 'The published copy of a TripEZGo trip. It opens in any browser — no app needed.',
    grid: 'Itinerary grid — scroll sideways for the other days',
    empty: 'Nothing planned for this day.',
    loading: 'Opening this trip…',
    copyApp: 'Copy to my trips',
    copyAppNote: 'With TripEZGo installed, the app opens and copies this trip into your own. Without it, this saves the link to your clipboard first — <b>install TripEZGo, open it, and it picks this trip up.</b>',
    savedHead: 'Link saved',
    savedLede: 'Now go and get TripEZGo. Open it once it’s installed, and it will offer to copy this trip.',
    savedGo: 'Go to the download',
    copyText: 'Copy as plain text', copiedText: 'Itinerary copied — paste it into any chat',
    cal: 'Schedule', map: 'Map', mapNone: 'No location — not on the map', mapAll: 'Nothing on this day has a location.',
    openApple: 'Apple Maps', openGoogle: 'Google Maps', close: 'Close',
    authorLink: 'I made this — manage the link',
    signinK: 'Manage this link', signinT: 'Sign in with iCloud',
    signinWhy: 'Sign in with the iCloud account that made this link to stop sharing it here.',
    signinGo: 'Continue to Apple sign-in',
    cancel: 'Cancel',
    ownerK: 'Signed in with iCloud', ownerT: 'You made this link',
    ownerWhy: 'No longer using TripEZGo? You can stop sharing right here.',
    stop: 'Stop sharing', signout: 'Sign out',
    stopAsk: 'Stop sharing this trip?',
    stopWhy: 'The link stops working straight away for everyone who has it. If you turn sharing back on in the app, it uses this same link again.',
    back: 'Back', stopped: 'Sharing stopped',
    stopFailed: 'Couldn’t stop sharing — please try again',
    notOwnerT: 'This iCloud account didn’t make this link',
    notOwnerWhy: 'Only the person who made the link can stop sharing it. Sign in with that account instead, or ask them to turn it off in the app.',
    stoppedT: 'Sharing stopped',
    stoppedWhy: 'This link no longer works. To share again, turn on the public link for this trip in TripEZGo — it will use the same link.',
    err: 'This trip could not be loaded', errWhy: 'The link may have expired, or sharing was turned off.',
    badT: 'This link is incomplete',
    badWhy: 'The trip can’t be unlocked. Ask them to copy the link again — the last part of the address (after the #) has to come with it.',
    learn: 'See what TripEZGo is',
    modes: { walking: 'Walking', driving: 'Driving', cycling: 'Cycling', transit: 'Transit', other: 'Other' },
  },
  ja: {
    days: '日間', day: '%s 日目', min: '%s 分', hr: '%s 時間', hrmin: '%s 時間 %s 分',
    undated: '日程未定', updated: '最終更新 %s',
    note: 'TripEZGo の旅程の公開版です。アプリがなくてもそのまま見られます。',
    grid: '旅程表——横にスクロールすると他の日が見られます',
    empty: 'この日はまだ予定がありません。',
    loading: 'この旅程を開いています⋯',
    copyApp: '自分の旅程にコピー',
    copyAppNote: 'TripEZGo が入っていればアプリが開き、この旅程を自分の旅程としてコピーします。まだの場合は、押すとこのリンクをクリップボードに保存します。<b>インストールしてアプリを開けば、この旅程につながります。</b>',
    savedHead: 'リンクを保存しました',
    savedLede: '続けて TripEZGo を入手してください。インストール後にアプリを開くと、この旅程をコピーするか尋ねます。',
    savedGo: 'ダウンロードへ',
    copyText: 'テキストでコピー', copiedText: '旅程をテキストでコピーしました',
    cal: 'スケジュール', map: '地図', mapNone: '位置情報なし（地図には出ません）', mapAll: 'この日は位置情報のある予定がありません。',
    openApple: 'Apple マップ', openGoogle: 'Google マップ', close: '閉じる',
    authorLink: '作成者の方：このリンクを管理',
    signinK: 'このリンクの管理', signinT: 'iCloud でサインイン',
    signinWhy: 'このリンクを作った iCloud アカウントでサインインすると、ここで共有を停止できます。',
    signinGo: 'Apple のサインインへ',
    cancel: 'キャンセル',
    ownerK: 'iCloud でサインイン中', ownerT: 'このリンクの作成者です',
    ownerWhy: 'TripEZGo を使っていなくても、ここで共有を停止できます。',
    stop: '共有を停止', signout: 'サインアウト',
    stopAsk: 'この旅程の共有を停止しますか？',
    stopWhy: '停止するとこのリンクはすぐに無効になり、誰も開けなくなります。アプリで共有をもう一度オンにすると、同じリンクがまた使われます。',
    back: '戻る', stopped: '共有を停止しました',
    stopFailed: '停止できませんでした。もう一度お試しください',
    notOwnerT: 'この iCloud アカウントは作成者ではありません',
    notOwnerWhy: '共有を停止できるのはリンクの作成者だけです。作成者のアカウントでサインインし直すか、アプリで停止してもらってください。',
    stoppedT: '共有を停止しました',
    stoppedWhy: 'このリンクは無効になりました。もう一度共有するには、TripEZGo でこの旅程の公開リンクをオンにしてください。同じリンクが使われます。',
    err: '旅程を読み込めませんでした', errWhy: 'リンクの有効期限が切れたか、共有が停止された可能性があります。',
    badT: 'このリンクは不完全です',
    badWhy: '旅程を開けませんでした。リンクをもう一度コピーしてもらってください。URL の最後の部分（# のあと）も必要です。',
    learn: 'TripEZGo について',
    modes: { walking: '徒歩', driving: '車', cycling: '自転車', transit: '公共交通', other: 'その他' },
  },
};

/** 去哪裡拿 App。**還沒上架**，所以跟 join/ 一樣先送回首頁（各語言那一份）；上架那天換成
 *  https://apps.apple.com/… 就好。 */
export const STORE = { zh: '/', en: '/en/', ja: '/ja/' };
