/* 分享活動頁的三語字典（網站有中、英、日三語，2026-10-10 使用者裁定先做這三語）。
 * 頁面上每一段字都從這裡來：HTML 裡的 data-t（純文字）／data-t-html（含 <strong>、連結，只放這裡寫死的字）。
 * {n}、{d} 由 app.js 代入。不提評分或評論（App Review Guidelines 3.2.2／5.6.3）。 */

export const LANGS = { 'zh-Hant': 'zh', en: 'en', ja: 'ja' };

/** <html lang> → 字典的鍵；認不得就用中文。 */
export function langKey(htmlLang) {
  return LANGS[htmlLang] || 'zh';
}

const APPLE_TERMS = 'https://www.apple.com/legal/internet-services/itunes/';

export const S = {
  zh: {
    title: '分享 TripEZGo，送你一年 Premium',
    lede: '在社群分享 TripEZGo，貼文附上 tripezgo.com 或 App Store 連結，就送你一組兌換碼：Premium 一年，到期不自動續訂。',
    eligibility: '限從沒訂閱過、或訂閱已到期的 Apple 帳號；已經買斷的朋友不必參加。數量有限，送完為止。',
    deadline: '活動到 {d}。',
    account: '目前登入：',
    switch: '換帳號',
    step1: '1. 選一則文案',
    captionsLabel: '文案',
    captionEdit: '可以再改一改（記得留著 tripezgo.com）',
    step2: '2. 分享到社群',
    more: '更多…',
    copyCaption: '複製文案（Instagram、PTT…）',
    publicNote: '貼文要設成<strong>公開</strong>，文案裡的 tripezgo.com 不要刪掉。',
    step3: '3. 把貼文網址貼回來',
    urlLabel: '公開貼文網址',
    paste: '從剪貼簿貼上',
    platforms: 'Threads、Instagram、Facebook、X、Bluesky、Mastodon、PTT、Plurk 都可以，其他公開網頁也收。',
    consent: '我同意 TripEZGo 保存我的 Google email 與這個貼文網址（永久保存，用於審核與防止重複領取），並讀取這個公開網址的內容來檢查。',
    remaining: '這個帳號還可以送 {n} 次。',
    submit: '送出',
    checking: '檢查中…',
    pendingTitle: '審核中',
    pendingBody: '這篇需要人工確認，審完之後用同一個帳號登入這一頁就看得到結果。',
    issuedTitle: '審核成功',
    issuedLead: '這是你的兌換碼：',
    redeem: '前往 App Store 兌換',
    issuedNote: '兌換碼建立後最多要 1 小時才能兌換；之後登入這一頁，隨時看得到同一組碼。',
    fine: [
      '數量有限，送完為止；兌換碼須在有效期限內兌換。',
      '可在販售 TripEZGo 的所有 App Store 國家或地區兌換。',
      '需要 Apple 帳號，且該帳號從沒訂閱過 TripEZGo Premium，或訂閱已到期。',
      '本兌換碼不得轉售，無現金價值。',
      `適用 <a href="${APPLE_TERMS}" target="_blank" rel="noopener">Apple 媒體服務條款與條件</a>。`,
      '本優惠與內容由 TripEZGo 提供，與 Apple 無關。',
    ],
    deniedTitle: '已參加活動',
    deniedBody: '這個帳號已經參加過，這次沒有通過審核。謝謝你的分享。',
    closedTitle: '活動已經結束',
    closedBody: '謝謝你的參與。',
    error: '出了點問題，請稍後再試。',
    hintAfter: '發好之後，把那篇貼文的網址貼到第 3 步。',
    hintCopied: '文案已經複製好了，到貼文裡貼上就行。發好之後，把那篇貼文的網址貼到第 3 步。',
    hintCopyFailed: '請手動複製上面的文案貼到貼文裡。發好之後，把那篇貼文的網址貼到第 3 步。',
    hintNotUrl: '剪貼簿裡不是網址。到貼文的「分享」或「複製連結」拿網址，再按一次。',
    hintNoClipboard: '這個瀏覽器不讓網頁讀剪貼簿，請直接在欄位裡貼上。',
    reasons: {
      'no-mention': '這篇貼文裡找不到 tripezgo.com 或 TripEZGo 的 App Store 連結。只寫名字不算，請把連結加進貼文內容。',
      unreachable: '讀不到這篇貼文。請確認貼文是公開的，網址是貼文本身（不是個人首頁）。',
      'duplicate-url': '這篇貼文已經被其他帳號用過了。',
      url: '這看起來不是社群貼文的網址。',
      consent: '請先勾選同意。',
    },
    captions: [
      '下一趟旅行的行程，我都排在 TripEZGo 裡：行程放行事曆、交通排時間軸，地圖、待辦、筆記都跟著這一趟走，沒有網路也看得到。\n👉 tripezgo.com\n#TripEZGo #旅行規劃',
      '排行程終於不用再開表格自己算時間了。TripEZGo 把每天的行程、路程和票券收在同一個 App，還能跟旅伴一起編。\ntripezgo.com',
      '出發前一晚不用再整理 Excel 了 😂 這次用 TripEZGo 一天一天把行程拉好，地圖上看得到每天怎麼走。\ntripezgo.com #旅行規劃',
      '推一個 iPhone／iPad 上的旅行規劃 App：TripEZGo。行事曆排行程、地圖看每日路線、多人共筆，免費就能開始。\ntripezgo.com',
    ],
  },

  en: {
    title: 'Share TripEZGo, get a year of Premium',
    lede: 'Share TripEZGo on social media with a link to tripezgo.com or the App Store, and we’ll send you a code for one year of Premium. It does not renew automatically.',
    eligibility: 'For Apple Accounts that have never subscribed, or whose subscription has expired; if you bought Premium outright you don’t need this. While codes last.',
    deadline: 'Ends {d}.',
    account: 'Signed in as ',
    switch: 'Switch account',
    step1: '1. Pick a caption',
    captionsLabel: 'Captions',
    captionEdit: 'Edit it if you like (keep tripezgo.com in it)',
    step2: '2. Share it',
    more: 'More…',
    copyCaption: 'Copy caption (Instagram and others)',
    publicNote: 'Make the post <strong>public</strong>, and keep tripezgo.com in the text.',
    step3: '3. Paste the post’s link back here',
    urlLabel: 'Link to your public post',
    paste: 'Paste from clipboard',
    platforms: 'Threads, Instagram, Facebook, X, Bluesky, Mastodon, PTT and Plurk all work, and so does any other public page.',
    consent: 'I agree that TripEZGo keeps my Google email and this post link (permanently, to review entries and prevent duplicates) and reads this public page to check it.',
    remaining: 'This account can submit {n} more time(s).',
    submit: 'Submit',
    checking: 'Checking…',
    pendingTitle: 'Under review',
    pendingBody: 'This post needs a person to look at it. Sign in to this page with the same account later to see the result.',
    issuedTitle: 'Approved',
    issuedLead: 'Here is your code:',
    redeem: 'Redeem on the App Store',
    issuedNote: 'A new code can take up to an hour before it can be redeemed. Sign in to this page any time to see the same code again.',
    fine: [
      'While supplies last; redeem the code before it expires.',
      'Redeemable in every App Store country or region where TripEZGo is available.',
      'Requires an Apple Account that has never subscribed to TripEZGo Premium, or whose subscription has expired.',
      'Not for resale. No cash value.',
      `Subject to the <a href="${APPLE_TERMS}" target="_blank" rel="noopener">Apple Media Services Terms and Conditions</a>.`,
      'Offer and content are provided by TripEZGo, not Apple.',
    ],
    deniedTitle: 'Already entered',
    deniedBody: 'This account has already taken part, and this entry wasn’t approved. Thanks for sharing.',
    closedTitle: 'This offer has ended',
    closedBody: 'Thanks for taking part.',
    error: 'Something went wrong. Please try again later.',
    hintAfter: 'Once it’s posted, paste the post’s link in step 3.',
    hintCopied: 'The caption is copied — paste it into your post. Once it’s posted, paste the post’s link in step 3.',
    hintCopyFailed: 'Please copy the caption above into your post. Once it’s posted, paste the post’s link in step 3.',
    hintNotUrl: 'The clipboard doesn’t hold a link. Use “Share” or “Copy link” on your post, then try again.',
    hintNoClipboard: 'This browser won’t let the page read the clipboard. Paste into the field instead.',
    reasons: {
      'no-mention': 'We couldn’t find tripezgo.com or the TripEZGo App Store link in this post. The name alone doesn’t count — please add the link to the post.',
      unreachable: 'We couldn’t read this post. Make sure it’s public and that the link is to the post itself, not a profile.',
      'duplicate-url': 'Another account has already used this post.',
      url: 'This doesn’t look like a link to a social media post.',
      consent: 'Please tick the box to agree first.',
    },
    captions: [
      'All my trip plans live in TripEZGo now: events on a calendar, travel on a timeline, and the map, to-dos and notes stay with the trip — even offline.\n👉 tripezgo.com\n#TripEZGo #travelplanning',
      'No more spreadsheets and doing the time maths myself. TripEZGo keeps each day’s plans, travel and tickets in one app, and my travel buddies can edit it too.\ntripezgo.com',
      'Packed the itinerary the night before without a spreadsheet for once 😂 Planned it day by day in TripEZGo and can see each day’s route on the map.\ntripezgo.com #travel',
      'A travel-planning app for iPhone and iPad I like: TripEZGo. Calendar for the plans, a map of each day’s route, plan together with friends — and it’s free to start.\ntripezgo.com',
    ],
  },

  ja: {
    title: 'TripEZGo をシェアして、Premium を 1 年分プレゼント',
    lede: 'SNS で TripEZGo を紹介して、tripezgo.com か App Store のリンクを投稿に入れてくれた方に、Premium 1 年分のコードをお送りします。自動更新はされません。',
    eligibility: '一度もサブスクリプションを登録したことがない、または期限が切れた Apple アカウントが対象です。買い切りで購入済みの方は参加不要です。なくなり次第終了します。',
    deadline: '{d} まで。',
    account: 'ログイン中：',
    switch: 'アカウントを切り替える',
    step1: '1. 文面を選ぶ',
    captionsLabel: '文面',
    captionEdit: '自由に書き換えて OK（tripezgo.com は残してください）',
    step2: '2. SNS でシェア',
    more: 'その他…',
    copyCaption: '文面をコピー（Instagram など）',
    publicNote: '投稿は<strong>公開</strong>にして、文面の tripezgo.com は消さないでください。',
    step3: '3. 投稿のリンクを貼り付ける',
    urlLabel: '公開投稿のリンク',
    paste: 'クリップボードから貼り付け',
    platforms: 'Threads、Instagram、Facebook、X、Bluesky、Mastodon、PTT、Plurk に対応。その他の公開ページも受け付けます。',
    consent: 'TripEZGo が私の Google のメールアドレスとこの投稿のリンクを保存し（審査と重複防止のため永久に保存）、この公開ページの内容を読み取って確認することに同意します。',
    remaining: 'このアカウントはあと {n} 回送信できます。',
    submit: '送信',
    checking: '確認中…',
    pendingTitle: '審査中',
    pendingBody: 'この投稿は担当者が確認します。審査が終わったら、同じアカウントでこのページにログインすると結果が見られます。',
    issuedTitle: '審査を通過しました',
    issuedLead: 'あなたのコードはこちら：',
    redeem: 'App Store で引き換える',
    issuedNote: 'コードは発行から引き換え可能になるまで最大 1 時間かかります。このページにログインすれば、いつでも同じコードを確認できます。',
    fine: [
      'なくなり次第終了します。有効期限内に引き換えてください。',
      'TripEZGo を配信しているすべての国または地域の App Store で引き換えられます。',
      'TripEZGo Premium を一度も登録したことがない、またはサブスクリプションの期限が切れた Apple アカウントが必要です。',
      '転売禁止。換金はできません。',
      `<a href="${APPLE_TERMS}" target="_blank" rel="noopener">Apple メディアサービス利用規約</a>が適用されます。`,
      '本特典とコンテンツは TripEZGo が提供するもので、Apple によるものではありません。',
    ],
    deniedTitle: '参加済みです',
    deniedBody: 'このアカウントはすでに参加済みで、今回は審査を通過しませんでした。シェアしてくれてありがとうございます。',
    closedTitle: 'キャンペーンは終了しました',
    closedBody: 'ご参加ありがとうございました。',
    error: '問題が発生しました。しばらくしてからもう一度お試しください。',
    hintAfter: '投稿したら、その投稿のリンクを手順 3 に貼り付けてください。',
    hintCopied: '文面をコピーしました。投稿に貼り付けてください。投稿したら、そのリンクを手順 3 に貼り付けてください。',
    hintCopyFailed: '上の文面を手動でコピーして投稿に貼り付けてください。投稿したら、そのリンクを手順 3 に貼り付けてください。',
    hintNotUrl: 'クリップボードにリンクが入っていません。投稿の「共有」や「リンクをコピー」でリンクを取ってから、もう一度押してください。',
    hintNoClipboard: 'このブラウザではクリップボードを読み取れません。欄に直接貼り付けてください。',
    reasons: {
      'no-mention': 'この投稿に tripezgo.com か TripEZGo の App Store リンクが見つかりませんでした。名前だけでは対象外です。投稿にリンクを入れてください。',
      unreachable: 'この投稿を読み取れませんでした。投稿が公開になっているか、リンクがプロフィールではなく投稿そのものか確認してください。',
      'duplicate-url': 'この投稿は別のアカウントですでに使われています。',
      url: 'SNS の投稿のリンクではないようです。',
      consent: '先に同意のチェックを入れてください。',
    },
    captions: [
      '次の旅の予定は全部 TripEZGo で。予定はカレンダー、移動はタイムライン、地図や ToDo、メモも旅ごとにまとまって、オフラインでも見られる。\n👉 tripezgo.com\n#TripEZGo #旅行計画',
      'もう表計算で時間を計算しなくていい。TripEZGo なら毎日の予定、移動、チケットがひとつのアプリにまとまって、旅の仲間と一緒に編集もできる。\ntripezgo.com',
      '出発前夜に Excel をいじらなくて済んだ 😂 今回は TripEZGo で 1 日ずつ予定を組んで、地図で毎日のルートも確認。\ntripezgo.com #旅行',
      'iPhone／iPad の旅行計画アプリ、TripEZGo がおすすめ。カレンダーで予定、地図で毎日のルート、みんなで共同編集。無料で始められます。\ntripezgo.com',
    ],
  },
};
